#!name=Locket Gold 🏅- Nguyễn Ngọc Anh Tú
#!desc=Mở khoá premium cho ứng dụng Locket Widget 
# 👤 Author: Nguyễn Ngọc Anh Tú 
# 💬 Facebook: fb.com/NguyenNgocAnhTu.VN 
# 🚀 Released by: Nguyễn Ngọc Anh Tú
#!version= 5
update-url = https://raw.githubusercontent.com/AnhTuKaZe/Locket/refs/heads/main/LOCKETGOLDNEW.module

[Script]
# ～ Egern transfer to Shadowrocket & Surge & LanceX

revenuecat = type=http-response, pattern=^https:\/\/api\.revenuecat\.com\/.+\/(receipts$|subscribers\/[^/]+$), script-path=https://raw.githubusercontent.com/vuong2023/shad/main/js/Locket_Ohoang7.js, requires-body=true, max-size=-1, timeout=60

deleteHeader = type=http-request, pattern=^https:\/\/api\.revenuecat\.com\/.+\/(receipts|subscribers), script-path=https://raw.githubusercontent.com/vuong2023/shad/main/js/deleteHeader.js, timeout=60

[MITM]
hostname = %APPEND% api.revenuecat.com
