#!name=Alight Motion
#!desc=Unlock Alight Motion Premium
📢 KÊNH CẬP NHẬT
🖥 Facebook: NguyenNgocAnhTu.VN
🌐 Luôn cập nhật các .sgmodule mới nhất, tối ưu, dễ dùng, an toàn.

[General]
bypass-system = true
skip-proxy = *.local, *.crashlytics.com
tun-excluded-routes = 192.168.0.0/16, 10.0.0.0/8, 172.16.0.0/12

[MITM]
hostname = api.revenuecat.com, buy.itunes.apple.com, us-central1-alight-creative.cloudfunctions.net

[Script]
http-response https://us-central1-alight-creative.cloudfunctions.net/getAccountStatusAndLicenses script-path=https://raw.githubusercontent.com/quocchienn/Make/refs/heads/crack/AlightMotion.js, requires-body=true, timeout=5, tag=Alight Motion

#!author=Quoc Chien
