#!name=Locket Gold V2
#!desc=Unlock Locket Gold
📢 KÊNH CẬP NHẬT
🖥 Facebook: NguyenNgocAnhTu.VN
🌐 Luôn cập nhật các .sgmodule mới nhất, tối ưu, dễ dùng, an toàn.

[Script]
revenuecat = type=http-response, pattern=^https:\/\/api\.revenuecat\.com\/.+\/(receipts$|subscribers\/[^/]+$), script-path=https://raw.githubusercontent.com/quocchienn/lockcrack/refs/heads/module/Locket_Gold.js, requires-body=true, max-size=-1, timeout=60

deleteHeader = type=http-request, pattern=^https:\/\/api\.revenuecat\.com\/.+\/(receipts|subscribers), script-path=https://raw.githubusercontent.com/quocchienn/lockcrack/refs/heads/module/deleteheader.js, timeout=60

[MITM]
hostname = %APPEND% api.revenuecat.com
